// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Board = require("./Board.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Logic = require("./logic.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("MyCounter");

function appReducer(action, state) {
  if (action) {
    return /* Update */Block.__(0, [/* record */[/* game */Logic.runPlayerTurn(state[/* game */0], /* Hit */0)]]);
  } else {
    return /* Update */Block.__(0, [/* record */[/* game */Logic.dealInitialcards(state[/* game */0])]]);
  }
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var game = param[/* state */1][/* game */0];
              return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Board.make(Belt_List.toArray(game[/* board */0][/* playerHand */0]), Belt_List.toArray(game[/* board */0][/* dealerHand */1]), /* array */[])), React.createElement("div", undefined, React.createElement("button", {
                                  onClick: (function () {
                                      return Curry._1(send, /* Deal */0);
                                    })
                                }, "Deal Cards")), React.createElement("div", undefined, React.createElement("button", {
                                  onClick: (function () {
                                      return Curry._1(send, /* HitMe */1);
                                    })
                                }, "Hit Me")));
            }),
          /* initialState */(function () {
              var shuffledDeck = Belt_List.shuffle(Logic.defaultDeck);
              return /* record */[/* game : record */[
                        /* board */Logic.emptyBoard,
                        /* deck */shuffledDeck,
                        /* gameState : NewGame */0
                      ]];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */appReducer,
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.appReducer = appReducer;
exports.make = make;
/* component Not a pure module */
