// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var Hand = require("./Hand.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Board");

var board = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.justifyContent(Css.center),
          /* :: */[
            Css.backgroundColor(Css.darkolivegreen),
            /* :: */[
              Css.minHeight(Css.px(500)),
              /* :: */[
                Css.margin(Css.px(10)),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var topStyle = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* [] */0
    ]);

var middleStyle = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.justifyContent(Css.center),
        /* :: */[
          Css.fontSize(Css.px(100)),
          /* [] */0
        ]
      ]
    ]);

var bottomStyle = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.justifyContent(Css.flexEnd),
        /* [] */0
      ]
    ]);

function actionButton(disabled) {
  return Css.style(/* :: */[
              Css.background(disabled ? Css.darkgray : Css.white),
              /* :: */[
                Css.color(Css.black),
                /* :: */[
                  Css.border(Css.px(1), Css.solid, Css.black),
                  /* :: */[
                    Css.borderRadius(Css.px(3)),
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

var Styles = /* module */[
  /* board */board,
  /* topStyle */topStyle,
  /* middleStyle */middleStyle,
  /* bottomStyle */bottomStyle,
  /* actionButton */actionButton
];

function make(playerHand, dealerHand, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: board
                        }, ReasonReact.element(/* None */0, /* None */0, Hand.make(dealerHand, /* array */[])), ReasonReact.element(/* None */0, /* None */0, Hand.make(playerHand, /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.Styles = Styles;
exports.make = make;
/* component Not a pure module */
