// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function styleToString(style) {
  if (typeof style === "number") {
    switch (style) {
      case 0 : 
          return "Jack";
      case 1 : 
          return "Queen";
      case 2 : 
          return "King";
      case 3 : 
          return "Ace";
      
    }
  } else {
    return String(style[0]);
  }
}

function suitToString(style) {
  switch (style) {
    case 0 : 
        return "Jack";
    case 1 : 
        return "Queen";
    case 2 : 
        return "King";
    case 3 : 
        return "Ace";
    
  }
}

function cardValue(param) {
  var style = param[/* style */1];
  if (typeof style === "number") {
    return 10;
  } else {
    return style[0];
  }
}

function addAces(sumSoFar, aces) {
  return Belt_List.reduce(aces, sumSoFar, (function (a, _) {
                if ((a + 11 | 0) <= 21) {
                  return a + 11 | 0;
                } else {
                  return a + 1 | 0;
                }
              }));
}

function calculateHand(hand) {
  var aces = List.filter((function (param) {
            return param[/* style */1] === /* Ace */3;
          }))(hand);
  var noAceHand = List.filter((function (param) {
            return param[/* style */1] !== /* Ace */3;
          }))(hand);
  var sumWithoutAces = Belt_List.reduce(List.map(cardValue, noAceHand), 0, (function (prim, prim$1) {
          return prim + prim$1 | 0;
        }));
  return addAces(sumWithoutAces, aces);
}

function range(start, end_) {
  if (start >= end_) {
    return /* [] */0;
  } else {
    return /* :: */[
            start,
            range(start + 1 | 0, end_)
          ];
  }
}

var suits = /* :: */[
  /* Hearts */0,
  /* :: */[
    /* Clubs */3,
    /* :: */[
      /* Diamonds */1,
      /* :: */[
        /* Spades */2,
        /* [] */0
      ]
    ]
  ]
];

var faceCards = /* :: */[
  /* Ace */3,
  /* :: */[
    /* King */2,
    /* :: */[
      /* Queen */1,
      /* :: */[
        /* Jack */0,
        /* [] */0
      ]
    ]
  ]
];

var simpleCards = List.map((function (i) {
        return /* Simple */[i];
      }), range(2, 10));

var styles = List.append(faceCards, simpleCards);

var defaultDeck = Belt_List.reduce(suits, /* [] */0, (function (a, suit) {
        return List.append(a, Belt_List.map(styles, (function (style) {
                          return /* record */[
                                  /* suit */suit,
                                  /* style */style
                                ];
                        })));
      }));

function gameStateToString(state) {
  switch (state) {
    case 0 : 
        return "New Game";
    case 1 : 
        return "Player Turn";
    case 2 : 
        return "Blackjack";
    case 3 : 
        return "Push";
    case 4 : 
        return "Player Bust";
    case 5 : 
        return "Dealer Bust";
    case 6 : 
        return "Dealer Turn";
    case 7 : 
        return "Player Win";
    case 8 : 
        return "Dealer Blackjack";
    case 9 : 
        return "Dealer Win";
    
  }
}

function calculatePayout(game) {
  var match = game[/* gameState */2];
  switch (match) {
    case 2 : 
        return game[/* playerBet */3] * 3.0 / 2.0;
    case 3 : 
        return game[/* playerBet */3];
    case 5 : 
    case 7 : 
        return game[/* playerBet */3] * 2.0;
    case 0 : 
    case 1 : 
    case 4 : 
    case 6 : 
    case 8 : 
    case 9 : 
        return 0.0;
    
  }
}

function dealInitialCards(game) {
  var exit = 0;
  var match = game[/* deck */1];
  if (match) {
    var match$1 = match[1];
    if (match$1) {
      var match$2 = match$1[1];
      if (match$2) {
        var match$3 = match$2[1];
        if (match$3) {
          var restDeck = match$3[1];
          var playerHand_000 = match[0];
          var playerHand_001 = /* :: */[
            match$1[0],
            /* [] */0
          ];
          var playerHand = /* :: */[
            playerHand_000,
            playerHand_001
          ];
          var dealerHand_000 = match$2[0];
          var dealerHand_001 = /* :: */[
            match$3[0],
            /* [] */0
          ];
          var dealerHand = /* :: */[
            dealerHand_000,
            dealerHand_001
          ];
          var initialGameState = calculateHand(playerHand) === 21 ? /* Blackjack */2 : /* PlayerTurn */1;
          var dealtGameState_000 = /* board : record */[
            /* playerHand */playerHand,
            /* dealerHand */dealerHand
          ];
          var dealtGameState_003 = /* playerBet */game[/* playerBet */3];
          var dealtGameState_004 = /* playerTotal */game[/* playerTotal */4];
          var dealtGameState = /* record */[
            dealtGameState_000,
            /* deck */restDeck,
            /* gameState */initialGameState,
            dealtGameState_003,
            dealtGameState_004
          ];
          return /* record */[
                  dealtGameState_000,
                  /* deck */restDeck,
                  /* gameState */initialGameState,
                  dealtGameState_003,
                  /* playerTotal */dealtGameState_004 + calculatePayout(dealtGameState) - dealtGameState_003
                ];
        } else {
          exit = 1;
        }
      } else {
        exit = 1;
      }
    } else {
      exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    throw [
          Caml_builtin_exceptions.match_failure,
          [
            "logic.re",
            144,
            6
          ]
        ];
  }
  
}

function dealerCanPlay(hand) {
  return calculateHand(hand) < 17;
}

function runDealerTurn(game) {
  return Belt_List.reduce(game[/* deck */1], game, (function (g, _) {
                var match = game[/* deck */1];
                if (match) {
                  var restDeck = match[1];
                  var newDealerHand_000 = match[0];
                  var newDealerHand_001 = game[/* board */0][/* dealerHand */1];
                  var newDealerHand = /* :: */[
                    newDealerHand_000,
                    newDealerHand_001
                  ];
                  if (calculateHand(g[/* board */0][/* dealerHand */1]) < 17) {
                    if (calculateHand(newDealerHand) <= 21) {
                      var init = game[/* board */0];
                      return /* record */[
                              /* board : record */[
                                /* playerHand */init[/* playerHand */0],
                                /* dealerHand */newDealerHand
                              ],
                              /* deck */restDeck,
                              /* gameState : DealerTurn */6,
                              /* playerBet */g[/* playerBet */3],
                              /* playerTotal */g[/* playerTotal */4]
                            ];
                    } else {
                      var init$1 = game[/* board */0];
                      return /* record */[
                              /* board : record */[
                                /* playerHand */init$1[/* playerHand */0],
                                /* dealerHand */newDealerHand
                              ],
                              /* deck */restDeck,
                              /* gameState : DealerBust */5,
                              /* playerBet */g[/* playerBet */3],
                              /* playerTotal */g[/* playerTotal */4]
                            ];
                    }
                  } else {
                    return g;
                  }
                } else {
                  throw [
                        Caml_builtin_exceptions.match_failure,
                        [
                          "logic.re",
                          176,
                          10
                        ]
                      ];
                }
              }));
}

function findWinner(board) {
  var playerTotal = calculateHand(board[/* playerHand */0]);
  var dealerTotal = calculateHand(board[/* dealerHand */1]);
  if (playerTotal === dealerTotal) {
    return /* Push */3;
  } else if (playerTotal > 21) {
    return /* PlayerBust */4;
  } else if (dealerTotal > 21) {
    return /* DealerBust */5;
  } else if (playerTotal > dealerTotal) {
    return /* PlayerWin */7;
  } else {
    return /* DealerWin */9;
  }
}

function runPlayerTurn(game, action) {
  switch (action) {
    case 0 : 
        return dealInitialCards(game);
    case 1 : 
        var match = game[/* deck */1];
        if (match) {
          var restDeck = match[1];
          var newPlayerHand_000 = match[0];
          var newPlayerHand_001 = game[/* board */0][/* playerHand */0];
          var newPlayerHand = /* :: */[
            newPlayerHand_000,
            newPlayerHand_001
          ];
          if (calculateHand(newPlayerHand) <= 21) {
            var init = game[/* board */0];
            return /* record */[
                    /* board : record */[
                      /* playerHand */newPlayerHand,
                      /* dealerHand */init[/* dealerHand */1]
                    ],
                    /* deck */restDeck,
                    /* gameState : PlayerTurn */1,
                    /* playerBet */game[/* playerBet */3],
                    /* playerTotal */game[/* playerTotal */4]
                  ];
          } else {
            var init$1 = game[/* board */0];
            return /* record */[
                    /* board : record */[
                      /* playerHand */newPlayerHand,
                      /* dealerHand */init$1[/* dealerHand */1]
                    ],
                    /* deck */restDeck,
                    /* gameState : PlayerBust */4,
                    /* playerBet */game[/* playerBet */3],
                    /* playerTotal */game[/* playerTotal */4]
                  ];
          }
        } else {
          throw [
                Caml_builtin_exceptions.match_failure,
                [
                  "logic.re",
                  232,
                  8
                ]
              ];
        }
    case 2 : 
        var dealerGame = runDealerTurn(game);
        var gameResult;
        if (dealerGame[/* gameState */2] === /* DealerBust */5) {
          gameResult = dealerGame;
        } else {
          var winner = findWinner(dealerGame[/* board */0]);
          gameResult = /* record */[
            /* board */dealerGame[/* board */0],
            /* deck */dealerGame[/* deck */1],
            /* gameState */winner,
            /* playerBet */dealerGame[/* playerBet */3],
            /* playerTotal */dealerGame[/* playerTotal */4]
          ];
        }
        return /* record */[
                /* board */gameResult[/* board */0],
                /* deck */gameResult[/* deck */1],
                /* gameState */gameResult[/* gameState */2],
                /* playerBet */gameResult[/* playerBet */3],
                /* playerTotal */game[/* playerTotal */4] + calculatePayout(gameResult)
              ];
    case 3 : 
        throw [
              Caml_builtin_exceptions.match_failure,
              [
                "logic.re",
                229,
                2
              ]
            ];
    
  }
}

function canHit(game) {
  var match = game[/* gameState */2];
  if (match !== 1) {
    return false;
  } else {
    return true;
  }
}

function canStand(game) {
  var match = game[/* gameState */2];
  if (match !== 1) {
    return false;
  } else {
    return true;
  }
}

function canDeal(game) {
  var match = game[/* gameState */2];
  if (match !== 1) {
    return true;
  } else {
    return false;
  }
}

var faceCardValue = 10;

var aceHighValue = 11;

var aceLowValue = 1;

var maxValue = 21;

var testHand = /* :: */[
  /* record */[
    /* suit : Hearts */0,
    /* style : Jack */0
  ],
  /* :: */[
    /* record */[
      /* suit : Hearts */0,
      /* style : Simple */[1]
    ],
    /* [] */0
  ]
];

var emptyBoard = /* record */[
  /* playerHand : [] */0,
  /* dealerHand : [] */0
];

var dealerHitValue = 17;

exports.styleToString = styleToString;
exports.suitToString = suitToString;
exports.faceCardValue = faceCardValue;
exports.cardValue = cardValue;
exports.aceHighValue = aceHighValue;
exports.aceLowValue = aceLowValue;
exports.maxValue = maxValue;
exports.addAces = addAces;
exports.calculateHand = calculateHand;
exports.testHand = testHand;
exports.range = range;
exports.suits = suits;
exports.faceCards = faceCards;
exports.simpleCards = simpleCards;
exports.styles = styles;
exports.defaultDeck = defaultDeck;
exports.emptyBoard = emptyBoard;
exports.gameStateToString = gameStateToString;
exports.calculatePayout = calculatePayout;
exports.dealInitialCards = dealInitialCards;
exports.dealerHitValue = dealerHitValue;
exports.dealerCanPlay = dealerCanPlay;
exports.runDealerTurn = runDealerTurn;
exports.findWinner = findWinner;
exports.runPlayerTurn = runPlayerTurn;
exports.canHit = canHit;
exports.canStand = canStand;
exports.canDeal = canDeal;
/* simpleCards Not a pure module */
