// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function cardValue(param) {
  var style = param[/* style */1];
  if (typeof style === "number") {
    return 10;
  } else {
    return style[0];
  }
}

function addAces(sumSoFar, aces) {
  return Belt_List.reduce(aces, sumSoFar, (function (a, _) {
                if ((a + 11 | 0) <= 21) {
                  return a + 11 | 0;
                } else {
                  return a + 1 | 0;
                }
              }));
}

function calculateHand(hand) {
  var aces = List.filter((function (param) {
            return param[/* style */1] === /* Ace */0;
          }))(hand);
  var noAceHand = List.filter((function (param) {
            return param[/* style */1] !== /* Ace */0;
          }))(hand);
  var sumWithoutAces = Belt_List.reduce(List.map(cardValue, noAceHand), 0, (function (prim, prim$1) {
          return prim + prim$1 | 0;
        }));
  return addAces(sumWithoutAces, aces);
}

function range(start, end_) {
  if (start >= end_) {
    return /* [] */0;
  } else {
    return /* :: */[
            start,
            range(start + 1 | 0, end_)
          ];
  }
}

var suits = /* :: */[
  /* Hearts */0,
  /* :: */[
    /* Clubs */3,
    /* :: */[
      /* Diamonds */1,
      /* :: */[
        /* Spades */2,
        /* [] */0
      ]
    ]
  ]
];

var simpleCards = List.map((function (i) {
        return /* Simple */[i];
      }), range(2, 10));

var styles = List.append(/* :: */[
      /* Ace */0,
      /* :: */[
        /* King */1,
        /* :: */[
          /* Queen */2,
          /* :: */[
            /* Jack */3,
            /* [] */0
          ]
        ]
      ]
    ], simpleCards);

var defaultDeck = List.map2((function (suit, style) {
        return /* record */[
                /* suit */suit,
                /* style */style
              ];
      }), suits, styles);

var faceCardValue = 10;

var aceHighValue = 11;

var aceLowValue = 1;

var maxValue = 21;

var testHand = /* :: */[
  /* record */[
    /* suit : Hearts */0,
    /* style : Jack */3
  ],
  /* :: */[
    /* record */[
      /* suit : Hearts */0,
      /* style : Simple */[1]
    ],
    /* [] */0
  ]
];

exports.faceCardValue = faceCardValue;
exports.cardValue = cardValue;
exports.aceHighValue = aceHighValue;
exports.aceLowValue = aceLowValue;
exports.maxValue = maxValue;
exports.addAces = addAces;
exports.calculateHand = calculateHand;
exports.testHand = testHand;
exports.range = range;
exports.suits = suits;
exports.simpleCards = simpleCards;
exports.styles = styles;
exports.defaultDeck = defaultDeck;
/* simpleCards Not a pure module */
