// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ArrayLabels = require("bs-platform/lib/js/arrayLabels.js");

function range($staropt$star, end_) {
  var start = $staropt$star ? $staropt$star[0] : 0;
  if (start >= end_) {
    return /* [] */0;
  } else {
    return /* :: */[
            start,
            range(/* Some */[start + 1 | 0], end_)
          ];
  }
}

function repeat(times, l) {
  return Belt_Array.map(ArrayLabels.of_list(range(/* None */0, times)), (function () {
                return l;
              }));
}

function cycle(times, l) {
  return Belt_List.concatMany(repeat(times, l));
}

exports.range = range;
exports.repeat = repeat;
exports.cycle = cycle;
/* No side effect */
